/**
 * The shape of the blog's content.
 *
 * The data itself is generated by scripts/extract-blog-content.ts from the
 * WordPress REST capture (seo-backup/03-wp-rest/posts.json):
 *
 *  - src/content/blog/index.generated.ts — one small summary per post, newest
 *    first. The only blog data the listing, the category archive and the
 *    related-posts band import.
 *  - src/content/blog/posts/<slug>.ts — one module per post, loaded lazily by
 *    that post's route alone, so no page carries the other 36 bodies.
 *
 * Titles, descriptions and H1s are deliberately not here — they come from the
 * SEO registry, which holds them to the live-site capture.
 */

/** One entry in the blog index. */
export interface BlogSummary {
  slug: string
  /** Live URL pathname, trailing slash included. Matches the registry record. */
  path: string
  /** The registry's H1, the post's title everywhere it is listed. */
  title: string
  /** ISO 8601 with offset, as WordPress published it. */
  published: string
  modified: string
  /** 1200x627 featured image. The 640-wide card rendition is `imageSmall`. */
  image: string
  imageSmall: string
  imageAlt: string
  readingMinutes: number
}

/**
 * Inline HTML inside a block. The extractor reduces it to `strong`, `em`, `br`
 * and `a` with an href (plus rel/target on external links) — no classes, no
 * styles, nothing a page has to sanitise again.
 */
export type InlineHtml = string

export type BlogBlock =
  | { type: 'p'; html: InlineHtml }
  /** Headings are plain text: the live headings' own bold/links add nothing the type scale doesn't. */
  | { type: 'h2' | 'h3' | 'h4'; id: string; text: string }
  | { type: 'list'; ordered: boolean; items: InlineHtml[] }
  | { type: 'table'; head: InlineHtml[] | null; rows: InlineHtml[][] }
  | { type: 'quote'; html: InlineHtml }
  | { type: 'video'; youtubeId: string; title: string }

export interface BlogTocEntry {
  id: string
  text: string
}

export interface BlogPostContent {
  slug: string
  blocks: BlogBlock[]
  /** The post's H2s, in order — what the live site's table of contents listed. */
  toc: BlogTocEntry[]
  /** The live post's "Medically reviewed" date, or null where it had none. */
  reviewedDate: string | null
  relatedSlugs: [string, string, string]
  /** fix-plan A2b: the service page a hub/spoke post links to. */
  serviceLink: { label: string; path: string } | null
}
